[workspace]
authors = ["Pete Peterson <peterfpeterson@gmail.com>"]
channels = ["conda-forge"]
name = "sunandmoon"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pre-commit = "*"
python = ">3.9"
ipython = "*"

[pypi-dependencies]
ephem = ">=4.2, <5"
